<?php

namespace AppBundle\Repository;

/**
 * OrderOfRingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrderOfRingRepository extends \Doctrine\ORM\EntityRepository
{
}
